package com.churchcac.pastorApp.utils;

public enum AppConstant {
    GENERAL_SUPERINTENDENT,
    REGIONAL_SUPERINTENDENT,
    DCC_ZONAL_SUPERINTENDENT,
    DISTRICT_SUPERINTENDENT,
    ASSEMBLY_CURATE_PASTOR,
    PRESIDENT,
    GENERAL_EVANGELIST,
    DIRECTOR_OF_MISSIONS,
    GENERAL_SECRETARY,
    FINANCE_DIRECTOR


    }
